Merged develop and fixed gradle build
jughyd/GitFx pull request #71
Opened 2017-02-06 19:11 UTC by rohitvvv

Synced up master and develop. Fixed the gradle build.

2017-02-06 19:13 UTC, rohitvvv commented
@jbuddha Please review.

2017-02-07 12:37 UTC, jbuddha requested changes

2017-02-07 12:37 UTC, jbuddha commented on .gitignore
> +>>>>>>> 834b8d3f0dd091cf4608cb6b496ff469a1905652
is this necessary? seems like a byproduct of resolving conflicts.

2017-02-07 12:37 UTC, jbuddha commented on src/main/java/io/github/gitfx/dialog/GitFxDialog.java
> +//[LOG]                  logger.debug(newValue.toString());
this listener may be removed as this is not doing anything

2017-02-07 12:50 UTC, jbuddha approved these changes

2017-02-07 12:52 UTC, merged